### ISSUE TITLE
Raw settings data should be camel case when a JSON file is the source

### ISSUE THREAD

**Issue by ntl** [eventide-project/settings#1]
Suppose I define a settings class with a JSON file as the data source:

``` ruby
class MySettings < ::Settings
  def self.data_source
    "settings/my_settings.json"
  end
end
```

The JSON file will be read and parsed into a `Hash` which is used as a data source. Right after `JSON.parse`, I think the library ought to use `Casing::Underscore` to convert all keys from camel case to underscore case. That way settings JSON files can use camel casing.

**Comment by sbellware** [comment]
This is repaired as of ee685a93ef90d48b204edbc49e4361940bd49200 and v0.1.0.2
