### ISSUE TITLE
Replace confstruct with use of Hash.dig

### ISSUE THREAD

**Issue by sbellware** [eventide-project/settings#3]
Removes `confstruct`, and `hashie`. Simplifies `settings` library.

We should list which features of `settings` would be affected, and whether we're comfortable removing those features. That said, many of the features of `settings` are never used.

**Comment by mbriggs** [comment]
you could make `settings.get(:a, :b, :c)` work, but `settings.data.a.b.c` wouldn't, since `settings.data` would become a hash.

**Comment by sbellware** [comment]
@mbriggs Yes, indeed, `settings.data.a.b.c` would no longer work. I think that's the "big" tradeoff. And it's not much of a loss. I don't think that feature has ever been used (or useful).

**Comment by sbellware** [comment]
Done
